name: storybook
description: A new Flutter project.
version: 0.0.2
homepage: https://github.com/zapiti/storybook

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_modular: ^3.3.1
  flutter_bloc: ^7.0.1
  collection: ^1.15.0
  google_fonts: ^2.1.0
  string_scanner: ^1.1.0
  device_frame: ^0.4.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
